server:
  port: 9876
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cmfz
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 400MB
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.baizhi.entity
